### ISSUE TITLE
[feature]provide a way to show the version of the TXLE server

### ISSUE THREAD

**Issue by asiroliu** [actiontech/txle#10]
# Describe The Bug  
As title, It is best to be accurate to the commit id

**Comment by Gannalyo** [comment]
Fixed.

To show version and 'commit id' by typing command 'txle -v' under the root directory of txle server, the result is as follows:
txle version 2.19.11.0 c2de6c28ab7df83af786ef3903785406f09b4463

**Comment by asiroliu** [comment]
```bash
# ./txle -v
txle version 2.19.11.0 07b3a392244141ac0549c51355c445ee9c05b9c9
```
