### ISSUE TITLE
[issue][alpha-server clustering]stop leader alpha-server, cause the global transaction failed

### ISSUE THREAD

**Issue by asiroliu** [actiontech/txle#15]
# Describe The Bug  
 stop leader alpha-server, cause the global transaction failed

# TXLE Version  
`https://github.com/actiontech/txle/commit/972b97cd664758ebca31eff09f05d3b7b360169d`

# To Reproduce  
1. install alpha server with clustering mode, and setup consul
2. use jmeter send http request trigger global transaction forever
3. stop leader alpha server

# Expected Result  
all global transaction should be successful and completed.

# Real Result  
the global transaction is failed, it try to connect alpha server which is stopped.

**Comment by Gannalyo** [comment]
Fixed in the '2.19.11.0' version.

**Comment by asiroliu** [comment]
verified in `txle version 2.19.11.0 07b3a392244141ac0549c51355c445ee9c05b9c9`
