### ISSUE TITLE
Please don't change the copyright if you didn't do anything on the code

### ISSUE THREAD

**Issue by WillemJiang** [actiontech/txle#17]
You can fork and change the code with the Apache License, but you cannot change the copyright if the code is not written by yourself, otherwise you are stealing the work from others.

**Comment by WillemJiang** [comment]
Please go through the [document](https://www.apache.org/legal/src-headers.html#3party) in the Apache about the third party source file.
You cannot change the License header of source as you are not the copyright owner or owner's agent.

**Comment by WillemJiang** [comment]
Here is a free course about the License and copyright in Open Source development.
https://training.linuxfoundation.cn/course/4
You cannot change the copyright statement unless you made a significant change on the source code.

**Comment by Gannalyo** [comment]
Hi Jiang, we are handling this event. And we will give a reply to you within 2 days as possible as we can.

**Comment by WillemJiang** [comment]
能加copyright前提是你对文件进行大范围的修改！
ServiceComb Pack之前的版权声明是在NOTICE文件中的， 把我们的代码NOTICE文件删了是何目的？
不能把文件头换来换去就当成你们做了实质工作就可以在文件上面加上你们公司的copyright！
代码都是有提交记录的，建议你把所有的文件都过一遍再在copyright，在不是你写的代码里加上copyright 就是赤裸裸的抄袭！！！

还有为啥要做一个fork版本， 又不是上游不合你的PR？
兄弟， 搞开源还是要讲讲公德的好吧！

**Comment by Gannalyo** [comment]
嗨  江工我们这面做了一些调整  在核心逻辑改动或改动较大的文件中加了我们的copyright  其它你们的文件仍保留你们的copyright  后续还有什么问题  我们随时沟通  带来的不便  还请谅解

**Comment by WillemJiang** [comment]
copyright的问题在还没确认解决完之前，请不要关闭问题。

**Comment by Gannalyo** [comment]
@WillemJiang 嗨  江  这面先reopen  有什么问题我们保持沟通  如果觉得没问题  再进行close

**Comment by Gannalyo** [comment]
嗨  江工  看您近一周没有响应该issue且我们这面已经处理了copyright问题  所以这面先关闭掉该issue

**Comment by Gannalyo** [comment]
嗨 江工 看您近一周没有响应该issue
且我们这面已经处理了copyright问题
所以这面先关闭掉该issue
